export const properties=[
    {
        id:1,
        title:"Palm Harbor",
        price:2700,
        adress:"2699 Green Valley, HighLand Lake, FL, USA",
        beds:3,
        bathrooms:3,
        area:'9*4',
        image:"https://th.bing.com/th/id/OIP.1cXyJGkZJl9T5vVvgAcd0wHaEh?w=310&h=189&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        location:"NewYork USA",
        moveby:[2022,8,3],
        category:"House"
    },
    {
        id:2,
        title:"Manshion",
        price:1500,
        adress:"City central, New delhi, India",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://pix8.agoda.net/hotelImages/564/564999/564999_15082114010034776993.jpg?ca=5&ce=1&s=1024x768",
        location:"Delhi India",
        moveby:[2022,12,29],
        category:"House"
    },
    {
        id:3,
        title:"Marne Avenue",
        price:4600,
        adress:"Green Valley, HighLand Lake, FL, USA",
        beds:2,
        bathrooms:2,
        area:`9*7`,
        image:"https://images.pexels.com/photos/2697773/pexels-photo-2697773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        location:"NewYork USA",
        moveby:[2022,9,10],
        category:"Store"
    },
    {
        id:4,
        title:"Marl borough",
        price:1000,
        adress:"9 Raffles Place #58-00 Republic Plaza, Singapore",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Singapore",
        moveby:[2025,8,4],
        category:"House"
    },
    {
        id:5,
        title:"Windsor site",
        price:3400,
        adress:"24 Jalan Tukang, Italy",
        beds:2,
        bathrooms:2,
        area:`6*7`,
        image:"https://images.pexels.com/photos/305832/pexels-photo-305832.jpeg?auto=compress&cs=tinysrgb&w=600",
        location:"Italy",
        moveby:[2022,8,5],
        category:"Store"
    },
    {
        id:6,
        title:"Lilac gorve",
        price:2200,
        adress:"50 BUKIT BATOK STREET 23#07-17, USA",
        beds:3,
        bathrooms:2,
        area:`5*7`,
        image:"https://images.pexels.com/photos/2260824/pexels-photo-2260824.jpeg?auto=compress&cs=tinysrgb&w=600",
        location:"New York USA",
        moveby:[2023,1,10],
        category:"Store"
    },
    {
        id:7,
        title:"Charn Wood",
        price:1200,
        adress:" 22-6-672/4, Mir Alam Mandi, Hyd, India",
        beds:2,
        bathrooms:2,
        area:`6*8`,
        image:"https://images.pexels.com/photos/296109/pexels-photo-296109.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Andhra pradesh India",
        moveby:[2022,8,2],
        category:"House",
    },
    {
        id:8,
        title:"Warwick",
        price:1700,
        adress:"5776, Sadar Bazar, India",
        beds:2,
        bathrooms:2,
        area:`6*8`,
        image:"https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Delhi India",
        moveby:[2023,4,15],
        category:"House",
    },
    {
        id:9,
        title:"Bentinck site",
        price:2800,
        adress:" 460 Milford Street, Europe",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://images.pexels.com/photos/833192/pexels-photo-833192.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Paris Europe",
        moveby:[2022,8,1],
        category:"House",
    },
    {
        id:10,
        title:"Trafalgar",
        price:3600,
        adress:"E1/75 Sector 11, Ymca Road, Delhi, India",
        beds:2,
        bathrooms:2,
        area:`6*8`,
        image:"https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Delhi India",
        moveby:[2022,8,15],
        category:"House",
    },
    {
        id:11,
        title:"Queens home",
        price:1800,
        adress:" 266-b Abdul Rehman Street, Mandvi, Maharastra",
        beds:0,
        bathrooms:0,
        area:'3*4',
        image:"https://images.pexels.com/photos/6342356/pexels-photo-6342356.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Maharastra India",
        moveby:[2025,5,20],
        category:"Store",
    },
    {
        id:12,
        title:"Derby Home",
        price:2400,
        adress:" 22-6-672/4, Mir Alam Mandi, India",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://images.pexels.com/photos/2480608/pexels-photo-2480608.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Hyderabad India",
        moveby:[2022,8,5],
        category:"House",
    },
    {
        id:13,
        title:"Mana homes",
        price:5000,
        adress:"2,1/12nwbelrd1stmnrdrmv2nblr-94, Rmv, India",
        beds:2,
        bathrooms:2,
        area:`6*8`,
        image:"https://images.pexels.com/photos/7031407/pexels-photo-7031407.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Banglore Karnataka India",
        moveby:[2026,4,10],
        category:"House",
    },
    {
        id:14,
        title:"Becketts Site",
        price:7900,
        adress:"3289 Hawks Nest Lane, USA",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://images.pexels.com/photos/8134745/pexels-photo-8134745.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"California USA",
        moveby:[2022,9,15],
        category:"House",
    },
    {
        id:15,
        title:"Saint Chads",
        price:2500,
        adress:"101, Swagatam, Junction 8 Th Rd & Sv Rd, Above Hdfc Bank, Khar (west), India",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/7031595/pexels-photo-7031595.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Chennai India",
        moveby:[2022,8,28],
        category:"House",
    },
    {
        id:16,
        title:"Tenry Banquet",
        price:800,
        adress:"47, Palika Bazar, Connaught Place, India",
        beds:6,
        bathrooms:6,
        area:`6*8`,
        image:"https://images.pexels.com/photos/4181670/pexels-photo-4181670.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Hyderabad India",
        moveby:[2022,9,30],
        category:"Banquet hall",
    },
    {
        id:17,
        title:"Suffolk home",
        price:2900,
        adress:" Mek Ind Complex A-29, India",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://images.pexels.com/photos/776938/pexels-photo-776938.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Chennai India",
        moveby:[2022,11,16],
        category:"House",
    },
    {
        id:18,
        title:"Camus luxuries",
        price:5000,
        adress:"8, 8, Rainbow Complex, Navrangpura, India",
        beds:15,
        bathrooms:15,
        area:`10*10`,
        image:"https://images.pexels.com/photos/382297/pexels-photo-382297.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Banglore India",
        moveby:[2022,10,14],
        category:"Banquet hall",
    },
    {
        id:19,
        title:"Alma's housie",
        price:650,
        adress:"4368 Williams Mine Road, USA",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Center USA",
        moveby:[2022,12,12],
        category:"House",
    },
    {
        id:20,
        title:"Rectory lane",
        price:900,
        adress:"4603 Sunrise Road, Europe",
        beds:3,
        bathrooms:2,
        area:`7*5`,
        image:"https://images.pexels.com/photos/2091166/pexels-photo-2091166.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Europe",
        moveby:[2022,8,2],
        category:"House",
    },
    {
        id:21,
        title:"Ack Worth homes",
        price:1400,
        adress:" Nr Saroday Hospital, Ghatkopar (west), Mumbai",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/3100371/pexels-photo-3100371.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Mumbai Maharastra India",
        moveby:[2022,12,5],
        category:"House",
    },
    {
        id:22,
        title:"West End Lanes",
        price:1900,
        adress:"4603 Sunset Road, Pune, India",
        beds:2,
        bathrooms:2,
        area:`6*8`,
        image:"https://media.istockphoto.com/photos/row-of-new-townhouses-or-condominiums-picture-id1060806178?b=1&k=20&m=1060806178&s=612x612&w=0&h=I08du9P9OT8RtklXPo8ZBRcs6bjm_uUJWgEp7-eC0Hk=",
        location:"Pune India",
        moveby:[2023,3,3],
        category:"House",
    },
    {
        id:23,
        title:"Lusitania",
        price:2900,
        adress:"Senapati Bapat Marg, Lower Parel (west), Jaipur",
        beds:0,
        bathrooms:1,
        area:'3*2',
        image:"https://images.pexels.com/photos/65438/pexels-photo-65438.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Jaipur India",
        moveby:[2022,8,14],
        category:"Store",
    },
    {
        id:24,
        title:"Nelson Home",
        price:4500,
        adress:"Hosur Main Rd, Madiwala, India",
        beds:12,
        bathrooms:12,
        area:`12*9`,
        image:"https://images.pexels.com/photos/1694360/pexels-photo-1694360.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Vijayawada Andhra Pradesh India",
        moveby:[2022,12,27],
        category:"Banquet hall",
    },
    {
        id:25,
        title:"Armory luxury",
        price:3800,
        adress:"Apos;souza Comp., Kharani Road, Andheri(e), India",
        beds:9,
        bathrooms:9,
        area:`10*8`,
        image:"https://images.pexels.com/photos/284991/pexels-photo-284991.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Mumbai India",
        moveby:[2022,12,1],
        category:"Banquet hall",
    },
    {
        id:26,
        title:"Scholar Park",
        price:1300,
        adress:"Kantilal Sharma Mrg, Lohar Chawl, Kalbadevi, India",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/404173/pexels-photo-404173.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Kerala India",
        moveby:[2023,1,10],
        category:"House",
    },
    {
        id:27,
        title:"Calderbug store",
        price:2200,
        adress:"Peston Sagar Road No 1, Chembur, Tilak Nagar, India",
        beds:0,
        bathrooms:1,
        area:`4*6`,
        image:"https://images.pexels.com/photos/747510/pexels-photo-747510.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Uttar Pradesh India",
        moveby:[2023,2,5],
        category:"Store",
    },
    {
        id:28,
        title:"Sark Walk Dinning",
        price:1680,
        adress:"1246 Fire Access Road, USA",
        beds:10,
        bathrooms:8,
        area:`12*9`,
        image:"https://images.pexels.com/photos/2832183/pexels-photo-2832183.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Washington USA",
        moveby:[2022,8,10],
        category:"Banquet hall",
    },
    {
        id:29,
        title:"Richings Way",
        price:6000,
        adress:"724 Heather Sees Way, USA",
        beds:2,
        bathrooms:2,
        area:'5*4',
        image:"https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Dallas USA",
        moveby:[2022,9,10],
        category:"House",
    },
    {
        id:30,
        title:"High Field store",
        price:4400,
        adress:"Geulstroom 146, Maldives",
        beds:0,
        bathrooms:1,
        area:`4*3`,
        image:"https://images.pexels.com/photos/880463/pexels-photo-880463.jpeg?auto=compress&cs=tinysrgb&w=400",
        location:"Maldives",
        moveby:[2022,8,20],
        category:"Store",
    }
]